[package]
name = "monoxide"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-channel = "0.5.15"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
sysinfo = "0.35.2"
thiserror = "2.0.12"
nvml-wrapper = "0.9"

